---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: test-requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: packer-dinivas-mosquitto
    image: centos:7
    groups:
      - consul_instances
    privileged: True
    command: '/sbin/init'
    cap_add: ['SYS_ADMIN', 'SETPCAP']
provisioner:
  name: ansible
  playbooks:
    converge: ../../playbook.yml
  env:
    OBJC_DISABLE_INITIALIZE_FORK_SAFETY: 'YES'
  lint:
    name: ansible-lint
verifier:
  name: goss
  lint:
    name: yamllint
